### ISSUE TITLE
general styling & typography issues

### ISSUE THREAD

**Issue by gwuzyx** [gameworkers/zine-gdc-2019-site#11]
- [x] `<blockquote>` styling
- [x] add ubuntu mono (or other monospace font) for unionfaqs instead of using native mono font stack (which doesn't look great everywhere)
- [x] shrink main container max-width (800px instead of 960? possibly even a bit smaller?) for more comfortable line length for reading
- [x] reduce/remove unionfaqs padding/margin on small screens
- [x] "GDC Zine 2019" text in header overflows awkwardly on mobile
- [x] bold or highlight currently active page in TOC
- [x] consider/check for any other scenarios where a breakpoint might be needed
- [x] distinguishing visually between UnionFAQs and normal articles in the table of contents view

**Comment by gwuzyx** [comment]
just ubuntu mono for unionfaqs font?

might be okay without a breakpoint, generally works on mobile. unionfaqs padding/margin could maybe be removed at lower resolution with a media query since it makes the reading width quite small.

@Acccent any opinions on this?

**Comment by gwuzyx** [comment]
might also want to shrink the main column a bit, 960px feels wide to me. it's a holdover from the original site but on there the text was a subset of the main col and would never be that wide.

**Comment by gwuzyx** [comment]
also the words "GDC Zine 2019" overflow to a new line on mobile

**Comment by leftTheBurnerOn** [comment]
I dealt with several of these. Adding an item for distinguishing visually between UnionFAQs and normal articles in the table of contents view

**Comment by gwuzyx** [comment]
@leftTheBurnerOn this wrapping is still pretty awkward to me on mobile... what if we just hide the text below a certain breakpoint?

![Screenshot from 2019-03-17 21-01-53](https://user-images.githubusercontent.com/48307851/54500893-f0778f00-48f7-11e9-89f7-fd424ab47b7d.png)

**Comment by gwuzyx** [comment]
i think all issues listed here are addressed!
