### ISSUE TITLE
integrate endnotes page

### ISSUE THREAD

**Issue by gwuzyx** [gameworkers/zine-gdc-2019-site#17]
already added to the project under `content/extradata/endnotes.md`, might need to be linked from somewhere on the site -- imo wherever we link to the pdf we should also link to the endnotes so they're easy to find when people come back from reading

**Comment by leftTheBurnerOn** [comment]
Agree, I'll add it below the pdfs in the footer in #8.

**Comment by leftTheBurnerOn** [comment]
I'm gonna add this comment to that issue, so closing.
