### ISSUE TITLE
older isabelle cover being used as the thumbnail

### ISSUE THREAD

**Issue by gwuzyx** [gameworkers/zine-gdc-2019-site#26]
![image](https://user-images.githubusercontent.com/48307851/54509576-6394fb80-4920-11e9-86c5-57daceafb2d4.png)

when you click through:

![image](https://user-images.githubusercontent.com/48307851/54509589-73144480-4920-11e9-9940-f130470df55a.png)

**Comment by leftTheBurnerOn** [comment]
fixed
