### ISSUE TITLE
if we want to use transparent isabelle image at large scale in intro, should probably use jpg+svg masking instead of png

### ISSUE THREAD

**Issue by leftTheBurnerOn** [gameworkers/zine-gdc-2019-site#4]

**Comment by leftTheBurnerOn** [comment]
Seems unimportant

**Comment by gwuzyx** [comment]
reopened but will remove from milestone? the image is pretty big, there might be a tool that can do an svg contour automatically....

**Comment by gwuzyx** [comment]
done, used https://codepen.io/shshaw/full/LVKEdv
